App/urls.py
from django.urls import path, re_path

from App import views

urlpatterns = [
    path('', views.index, name='index'),
    path('register', views.register, name='register'),
    path('logout', views.logout, name='logout'),
    path('login', views.login, name='login'),

    re_path('goods/(\d+)', views.goods, name='goods'),
    re_path('goods', views.goods, name='goods'),
    re_path('detail/(\d+)/(\d+)', views.detail, name='detail'),
    path('requesttest', views.requesttest, name='requesttest'),
    path('responsetest', views.responsetest, name='responsetest'),
    path('gettest', views.gettest, name='gettest'),
    path('show_static', views.show_static, name='show_static'),
    path('test_process_request', views.test_process_request, name='test_process_request'),


    path('goodlist', views.goodlist, name='goodlist'),
    path('addnew', views.addnew, name='addnew'),

    re_path('goodlist/(\d+)', views.goodlist, name='goodlist'),
    re_path('shownews', views.shownews, name='shownews'),
    re_path('shownewdetail/(\d+)', views.shownewdetail, name='shownewdetail'),

]

django0527/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('App.urls','App'),namespace="app"))

]

App/models.py
from django.db import models
# Create your models here.
from tinymce.models import HTMLField


class User(models.Model):
    username = models.CharField(max_length=80)
    password = models.CharField(max_length=240)
    tel = models.CharField(max_length=20)
    headimg = models.CharField(max_length=200,default=1)




class Goods(models.Model):
    name = models.CharField(max_length=20)
    icon = models.CharField(max_length=255)
    price = models.IntegerField()
    detail = models.CharField(max_length=255)

    class Meta:
        db_table = 'goods'
    #
    #
    # def __str__(self):
    #     return self.name


# 下面这两个表是用于测试 后台管理的级联关系
class Grade(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class student(models.Model):
    name = models.CharField(max_length=50)
    age = models.IntegerField()
    sex = models.CharField(max_length=50)

    s_grade = models.ForeignKey(Grade,on_delete='on_delete')

class News(models.Model):
    title = models.CharField(max_length=250)
    content = HTMLField()

App/views.py
import os

from django.core.paginator import Paginator
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect


# Create your views here.
from App.models import User, Goods, News
from django0527 import settings


def index(request):
    username = request.COOKIES.get('user','')
    headimg_path = ''

    if username:
        users = User.objects.values_list("headimg").filter(username=username)
        # filter(username=username)
        if users.count():
            # 获取到数据库中的 头像名称
            headimg_name = users[0][0]
            headimg_path = os.path.join('upload',headimg_name)

    return render(request,'index.html',context={'user':username,'headimg':headimg_path})


def register(request):
    if request.method == "GET":
        return render(request,"register.html")
    else:
        username = request.POST.get('username')
        password = request.POST.get('password')
        tel = request.POST.get('tel')
        headimg = request.FILES.get('headimg')
        headimg_name = '{}-{}'.format(username,headimg.name)

        filepath = os.path.join(settings.upload_path,headimg_name)
        # 获取到的头像写到本地
        with open(filepath,'wb') as f:
            for i in headimg.chunks():
                f.write(i)


        user = User()
        user.username = username
        user.password = password
        user.tel = tel
        user.headimg = headimg_name
        user.save()

        response = redirect("app:login")

        response.set_cookie("user",username)


        # return HttpResponse('{}{}{}'.format(username,password,tel))

        return response

def goods(request,num=0):
    return HttpResponse("这里是商品页，这里访问的页码是 {}".format(num))


def detail(request,a,b):
    return HttpResponse("测试url中含有多个参数{}，{}".format(a,b))


def requesttest(request):
    data = {
        "path":request.path,
        "methor":request.method,
        "get参数":request.GET
    }
    return render(request,'requesttest.html',context=data)


def gettest(request):
    name = request.GET.get('name')
    age = request.GET.get('age',10)
    return HttpResponse("get参数是：名字：{},年龄：{}".format(name,age))


def responsetest(request):
    response = HttpResponse('常规的文本输出返回')
    # 模板的返回
    response = render(request,"index.html")
    # 重定向 ， 本应该访问该视图， 重定向别的连接去了
    response = HttpResponseRedirect('/goods.html')
    # 另外一种重定向的方法
    response = redirect('/goods.html')

    # 视图里面的反向解析,可添加参数
    response = redirect('app:goods',13)
    # 重定向页可以添加参数
    # response = redirect('/goods.html',13)

    str1 = {
        "name":"123",
        "age":19
    }

    response = JsonResponse(str1)
    return response


def logout(request):
    response = HttpResponse("已退出登录")
    response.delete_cookie('user')
    return response


def login(request):
    if request.method =='GET':
        return render(request,"login.html")
    else:
        username = request.POST.get('username')
        password = request.POST.get('password')

        users = User.objects.filter(username=username).filter(password=password)
        if users.count() > 0:
            response = redirect("app:index")
            response.set_cookie("user",username)
        else:
            response = HttpResponse("账号或密码错误")
        return response


def show_static(request):
    return render(request,"show_static.html")


def test_process_request(request):
    return HttpResponse('测试路由分配的view函数')


def goodlist(request,page=1):
    goodlist = Goods.objects.all()
    # 对goodlist 所有商品 按每页 5个商品来分页
    paginator = Paginator(list(goodlist),5)
    # 获取当前页的商品
    pageObj = paginator.page(page)
    # 所有的页码
    pagelist = pageObj.paginator.page_range

    # 参数为页码，返回该页码的所有商品 + 所有的页码列表
    return render(request,'goodlist.html',context={'pageObj':pageObj, 'pagelist':pagelist})


def shownews(request):
    news = News.objects.all()
    return render(request,'shownews.html',context={'news':news})
    # return HttpResponse("新闻详情页")


def shownewdetail(request,new_id):
    new = News.objects.get(pk=int(new_id))

    # return HttpResponse("第{}条新闻".format(new_id))
    return render(request,'shownewdetail.html',context={"new":new})


def addnew(request):
    if request.method == 'GET':
        return render(request,'addnew.html')
    else:
        new = News()
        new.title = request.POST.get('title')
        new.content = request.POST.get('content')
        new.save()
        # return redirect("app:shownews")
        return HttpResponse("tianja")

templates/addnew.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加新闻页</title>
</head>
<body>

<script type="text/javascript" src="{% static 'tiny_mce/tiny_mce.js' %}"></script>
    <script>
        tinyMCE.init({
            'mode': 'textareas',
            'theme': 'advanced',
            'width': 1000,
            'height': 500,
        })
    </script>


<form action="{% url "app:addnew" %}" method="post">
    {% csrf_token %}
    <p>title: <input type="text" name="title"></p>
    <p>detail: <textarea name="content"></textarea></p>
    <input type="submit" values="添加">

</form>

</body>
</html>

templates/goodlist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>商品显示页</title>
</head>
{#    样式的添加还需要学习#}
   <style>
        * {
            margin: 0;
            padding: 0;
        }

        .main{
            width: 900px;
            margin: 10px auto;
        }

        li {
            list-style: none;
            border: 1px solid gray;
            overflow: hidden;
            padding: 10px;
            margin: 10px;
        }

        li .img {
            float: left;
            width: 100px;
            height: 100px;
            margin-right: 10px;
        }

        li .content {
            float: left;
        }

        li .content p {
            line-height: 25px;
        }

        li .content .name {
            font-weight: 800;
        }

        li .content .price {
            color: red;
        }

        li .content .detail {
            color: gray;
        }

        .pageController {

        }

        .pageController a {
            display: inline-block;
            width: 30px;
            height: 30px;
            border: 1px solid gray;
            margin: 5px;
            text-align: center;
            line-height: 30px;
            text-decoration: none;
        }
    </style>

<body>
{#        分页对象的每个商品，用 object_list #}
<div class="main">
    <ul>
      {% for goods in pageObj.object_list %}
            <li>
                <div class="img">
                    <img src="{{ goods.icon }}" alt="">
                </div>

                <div class="content">
                    <p class="name"> {{ goods.id }}-{{ goods.name }} </p>
                    <p class="price"> ￥{{ goods.price }} </p>
                    <p class="detail"> {{ goods.detail }} </p>
                </div>
            </li>
        {% endfor %}
    </ul>
</div>

<div class="pageController">
    {% for item in pagelist %}
        {% if item == pageObj.number %}
            <b> {{ item }} </b>
        {% elif item == None %}
            <b> ... </b>
        {% else %}
           <a href="{% url "app:goodlist" item %}"> {{ item }} </a>
        {% endif %}
    {% endfor %}
</div>






</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>这是app的首页</title>
    <style>
        img{
            border-radius: 50%;
            overflow: hidden;
            width: 200px;
            height: 200px
        ;
        }
    </style>
</head>
<body>
{% load static %}
{% if user %}
    <h2>用户：{{ user }},已登录</h2>
    <a href="{% url "app:logout" %}">退出登录</a>
{% else %}
<a href="{% url "app:register" %}">注册</a>
<a href="{% url "app:login" %}">登录</a>
{% endif %}


<form action="/test/" method="post">
    <input type="text" name="username" placeholder="用户名">
    <input type="submit" value="抽奖">
</form>


<a href="{% url "App:test_process_request" %}">测试process_request中间键
</a>

{% if headimg %}
    <div class="head">
    <img src="{% static headimg %}">
</div>
{% endif %}

<p>
    <h2>
<a href="{% url "app:goodlist" %}">点击查看商品</a>
    </h2>
</p>

<p>
    <h2>
<a href="{% url "app:shownews" %}">新闻展示页</a>
    </h2>
</p>


</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
</head>
<body>
<form action="{% url "app:login" %}" method="POST">

    {% csrf_token %}
    <p>
        账号：<input type="text" name="username" placeholder="请输入您的账号">
    </p>
    <p>
        密码：<input type="password" name = "password" placeholder="请输入您的密码">
    </p>
    <input type="submit" value="登录">

</form>


</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>这里是注册页</title>
</head>
<body>
<form action="{% url "app:register" %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <p>
        账号：<input type="text" name="username" placeholder="输入账号">
    </p>
    <p>
        密码：<input type="password" name="password" placeholder="输出密码">
    </p>
    <p>
        电话号码：<input type="text" name="tel" placeholder="输出电话号码">
    </p>
    <p>
        请上传头像：<input type="file" name="headimg" en>
    </p>
    <input type="submit" value="注册">

</form>

</body>
</html>

templates/requesttest.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>requesttest</title>
</head>
<body>
 路径：{{ path }}
 方法：{{ methor }}
 get参数：{{ get参数 }}

</body>
</html>

templates/show_static.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>静态文件测试</title>
</head>
<body>
<img src="/static/images/aa.png">

</body>
</html>

templates/shownewdetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>新闻详情页</title>
</head>
<body>

{{ new.content | safe}}

</body>
</html>

templates/shownews.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>新闻展示页</title>
</head>
<body>
<ul>
{% for new in news %}
    <li><a href="{% url "app:shownewdetail" new.id %}" >{{ new.title }}</a></li>
{% endfor %}

<p><a href="{% url "app:addnew" %}">添加新闻</a> </p>
</ul>


</body>
</html>